### ISSUE TITLE
Error: Invalid Identity

### ISSUE THREAD

**Issue by lloydkalicki** [blaise-io/contribution#1]
hi!  Is it me? 

Error: Invalid identity

**Comment by blaise-io** [comment]
This means GitHub doesn't recognize the user for your identity file. Was your contribution graph updated?

**Comment by blaise-io** [comment]
@lloydkalicki This means GitHub doesn't recognize the user for your identity file. Was your contribution graph updated? What does `ssh -vT git@github.com` give you?

**Comment by blaise-io** [comment]
Closed due to inactivity.
